### ISSUE TITLE
[Feature] ARWorldAlignment prop

### ISSUE THREAD

**Issue by conorstrejcek** [HippoAR/react-native-arkit#101]
It would be very beneficial for many applications to have the option to specify the ARWorldAlignment option when using ARKit. This option handles how ARKit aligns the Axes of its coordinate system, and has three options:

**ARWorldAlignmentGravity**
The coordinate system's y-axis is parallel to gravity, and its origin is the initial position of the device.

**ARWorldAlignmentGravityAndHeading**
The coordinate system's y-axis is parallel to gravity, its x- and z-axes are oriented to compass heading, and its origin is the initial position of the device.

**ARWorldAlignmentCamera**
The scene coordinate system is locked to match the orientation of the camera.

(taken from [Apple Documentation](https://developer.apple.com/documentation/arkit/arworldalignment))

I would suggest that this be a prop on the main `<ARKit />` component. I don't have a lot of experience with Native iOS code, so I am not sure how difficult this is to implement, but I hope it isn't too difficult.

**Comment by macrozone** [comment]
@conorstrejcek: that should be easy to implement.

you would export these constants (see here for an example: https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKitManager.m#L23) 

then you export a property like here: https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKitManager.m#L66

and define the property here: https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKit.h#L38

and its setter and getter https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKit.m#L127

and finally define this property as a new prop on the react component: https://github.com/HippoAR/react-native-arkit/blob/master/ARKit.js#L176

i hope, i did not miss anything.

would be cool to get a PR for that!

**Comment by conorstrejcek** [comment]
@macrozone I will attempt a pull request for this,

**Comment by conorstrejcek** [comment]
@macrozone I am getting an error from `RCTConvert+ARKit.m`:

 `'SVGBezierPath.h' file not found`

The project that I am testing the package in was working when I followed the instructions for manual installation, but when I started using a linked version of my local copy of the package, the XCode builds are failing on trying to import files from the PocketSVG framework. I checked the project, and the files are still a part of the Library in XCode, so I am not sure what is happening. Any insight you might have would be appreciated.

You can see below that the framework is still within the project. 

![screen shot 2017-10-30 at 12 02 27 pm](https://user-images.githubusercontent.com/2925090/32184465-5018f630-bd6a-11e7-9f7a-be80fd49d84a.png)

**Comment by conorstrejcek** [comment]
I just submitted a pull request for this feature: https://github.com/HippoAR/react-native-arkit/pull/102

**Comment by macrozone** [comment]
published as react-native-arkit@0.4.3
