### ISSUE TITLE
getCameraPosition doesn't return camera position

### ISSUE THREAD

**Issue by jamonholmgren** [HippoAR/react-native-arkit#12]
The `getCameraPosition` method doesn't seem to return the right values.

```javascript
    const cameraPosition = ARKit.getCameraPosition()

    alert(JSON.stringify(cameraPosition))
```

Result:

![img_4a114a06f6b7-1](https://user-images.githubusercontent.com/1479215/29728598-73e49bca-898d-11e7-80b8-e8c7487ce8c7.jpeg)

I have an iPhone 6s Plus.

I am looking into this, but figured I'd file an issue. If you have ideas or if your camera position works fine, please let me know, because that would be useful.

**Comment by jamonholmgren** [comment]
Having trouble tracking this down. Any help would be appreciated!

**Comment by markkurt** [comment]
The call to getCameraPosition returns a promise (i.e., the return from readCameraPosition here https://github.com/HippoAR/react-native-arkit/blob/master/ios/RCTARKitManager.m#L43).  So the correct way to call it from javascript is something like:

```
async function doSomethingWithCameraPosition() {
  var position = await ARKit.getCameraPosition();
  console.log(position); // now contains an x, y, z in a javascript structure
}

```

an alternative method would be to add a new method to the RCTARKitManager class that accepted a callback, but with the addition of ES6 async/await this keeps the javascript code cleaner.

**Comment by jamonholmgren** [comment]
Interesting, the documentation wasn't clear, and NSLog gave me the unhelpful output above. Thanks @markkurt for clearing that up.
