### ISSUE TITLE
Cannot read property 'target' of undefined- error while calling method snapshotCamera and snapshot

### ISSUE THREAD

**Issue by manu-codes** [HippoAR/react-native-arkit#125]
**Steps to reproduce-**
1. Call the function ARKit.snapshot or snapshotCamera 
Version of react-native-arkit - 0.6.0

**Expected result**
Save a snapshot
**Actual result**
Error Cannot read property 'target' of undefined
![screen](https://user-images.githubusercontent.com/2102862/33825702-81638f54-de88-11e7-958c-4977c789fea1.png)

**Comment by macrozone** [comment]
thanks for reporting that!

i did not check yet, but can you pass an empty object to the function?

and can you try the beta version? (yarn add react-native-arkit@beta)

**Comment by macrozone** [comment]
this has been fixed in 0.8.0
