### ISSUE TITLE
[Question]-Render image on object

### ISSUE THREAD

**Issue by Bickson** [HippoAR/react-native-arkit#126]
Hi, just wondering how to render image on object, should I use:

```
material={{
  color: 'red',
    normal: {
       path: require('myPicPath')
    }
}}
```

**Comment by macrozone** [comment]
hi Bickson.

@bnjm worked on that pr: https://github.com/HippoAR/react-native-arkit/pull/121

maybe he can help you with that.

i think you can just specify the path as string. And i think it also supports loading from local file system (require usually only works for static assets)

**Comment by Bickson** [comment]
thanks! would love an example for rendering a picture that is in the project ( haven't gotten it to work yet )

**Comment by bnjm** [comment]
Two possible issues here:

1. The pr #121 has not been released yet, so you'll need to make sure you are using what's in the current master branch

2. I ran into some problems with `path: require('path')`, as it seemed ARKit was just passed a number rather than the actual file. It works when you provide an absolute path to the `xc.assets/image` file. This feature needs some more testing and improvements.

**Comment by bnjm** [comment]
One way you can get the absolute path is by dropping the image into the Images.xcassets folder in xcode, then you can reference it in material like 

```
material={{
  diffuse: {
    path: 'assets/image-name-no-extension'
  }
}}
```
Will look into why it does not work with `require()`

**Comment by macrozone** [comment]
@bnjm for require you need another library from react native, but that wasn't documented the last time i checked.

**Comment by Bickson** [comment]
1. Thanks for answering so quickly!

2. I'm now running towards github#master and i added a ImageSet in `Images.xcassets` and trying a bunch of combination of paths ( feeling stupid :)
```
material={{
  normal: { path: 'assets/my-pic-name-without-.jpg-or-.png' }
}}
``` 
if i do `diffuse` and have a `intensity` value it changes so something works :)

**Comment by Bickson** [comment]
@bnjm @macrozone got it to work, draged the picture in drectly instead och creating a ImageSet thanks guys!
marry Christmas & happy New Years!

**Comment by cr-ks** [comment]
@Bickson I'm also trying to get this feature to work! I tried what you said above and still couldn't get it... could you expand on your solution?

Thanks!

**Comment by Bickson** [comment]
@cr-ks I just draged the image to the `Images.xcassets` folder in xcode
then you can access the picture from assets without extension.
```
material={{
              diffuse: { path: 'assets/pic-name-without-extension', intensity: 1 }
            }}
```
hope it helps

**Comment by macrozone** [comment]
I close this as it seems to be fixed
