### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by XavierColombel** [HippoAR/react-native-arkit#127]
I've got this error when I run the example. Any hint?

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_SVGBezierPath", referenced from:
      objc-class-ref in libRCTARKit.a(RCTConvert+ARKit.o)
ld: symbol(s) not found for architecture arm64
```

**Comment by XavierColombel** [comment]
I've reinstall manually, and it worked. I also had to keep only arm64 in Valid Architectures.

**Comment by stoneWeb** [comment]
How did you fix it?

**Comment by dr3d** [comment]
Yeah, how?

**Comment by XavierColombel** [comment]
As I told before I only left armv64 in Valid Architectures:
![Image](https://preview.ibb.co/grrP5o/FF8_F8_D2_B_F147_491_D_A1_EB_4087_DA489_AF0.jpg)
