### ISSUE TITLE
Draw a line between two points?

### ISSUE THREAD

**Issue by XavierColombel** [HippoAR/react-native-arkit#128]
Do you have an idea on drawing a line between two points?

**Comment by macrozone** [comment]
this is an example of a line. it uses a cyclinder to draw the line:

https://gist.github.com/macrozone/1760a8e978b8f219b757f04fbbd98c0a

**Comment by XavierColombel** [comment]
Hey thanks @macrozone! Which lib do you use for `vectorUtils`?

**Comment by macrozone** [comment]
@XavierColombel its just self-made atm (did not found a simple library for that, but would love to use one already existing). Here is what i use:

https://gist.github.com/macrozone/d25824762e22a8dedb08ca6ceb59a1fd

**Comment by XavierColombel** [comment]
You rock so much... 👍

**Comment by macrozone** [comment]
I'll close this for now :-)

**Comment by jackychanfox** [comment]
I want to draw 2D line on React View, which connects two 3D points
how can I get 2D point from 3D?
