### ISSUE TITLE
ARSCNViewDelegate methods don't appear to be running

### ISSUE THREAD

**Issue by seantempesta** [HippoAR/react-native-arkit#13]
I've tried breakpointing all of the ARSCNViewDelegate methods:
```
didAddNode
willUpdateNode
didUpdateNode
didRemoveNode
```
And none of them are running.  None of the `NSLog` messages are appearing either.

**Comment by macrozone** [comment]
is this still an issue with latest version?

**Comment by seantempesta** [comment]
Yeah.  I just tried it again and none of the plane detection code is running.

**Comment by macrozone** [comment]
@seantempesta: plane detection code is running. You can use onPlaneUpdate or onPlaneDetected callbacks. Can you show more context on your problem? E.g. show some code.

**Comment by macrozone** [comment]
@seantempesta is this still an issue? can it be closed?

**Comment by macrozone** [comment]
@seantempesta I'll close this one, but feel free to reopen!
