### ISSUE TITLE
How to use ARFaceTrackingConfiguration with react-native-arkit

### ISSUE THREAD

**Issue by DavidQL** [HippoAR/react-native-arkit#130]
I need to use the [ARFaceTrackingConfiguration](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration) option for my ARkit project. Is there a way to specify that class as the scene's configuration?

**Comment by macrozone** [comment]
@DavidQL not yet, but should be easy to add. Maybe you can try yourself and send a PR!

**Comment by macrozone** [comment]
duplicate of https://github.com/HippoAR/react-native-arkit/issues/154

**Comment by emphaticaditya** [comment]
any update on this?
