### ISSUE TITLE
Augmented Reality with React Native (Points of Interest over the camera) 

### ISSUE THREAD

**Issue by ashmanmalik** [HippoAR/react-native-arkit#136]
Hi i am trying to overlay the images in React-native AR, I am facing the following issues. 

1.  How could i be able to create a button and function to trigger the images. 
2. How can i convert the GPS coordinates to camera coordinates relative to X Y and Z axis. 
3. How can i create an Overlays on the camera? 

Any help would be appreciated as documentation doesn't have much details. Thanks!

**Comment by macrozone** [comment]
@ashmanmalik maybe the slack channel is better suited for questions like this: react-native-ar.slack.com

I also think you have to be more specific with your usecase as i don't really understand your request :-/
