### ISSUE TITLE
Vertical plane detection support

### ISSUE THREAD

**Issue by bnjm** [HippoAR/react-native-arkit#139]
With ARKit 1.5 (available with iOS 11.3) comes support for detecting vertical planes (also other cool stuff)

Seems like this could be added to the library at the following place:

https://github.com/HippoAR/react-native-arkit/blob/e75cd4c2f89782d0015343403165fd9ab34b0c12/ios/RCTARKit.m#L149

Will attempt a PR when I get some time, but maybe someone can beat me to it.

**Comment by macrozone** [comment]
Looking forward to try it out!

**Comment by macrozone** [comment]
available in https://github.com/HippoAR/react-native-arkit/releases/tag/0.9.0-beta.3
