### ISSUE TITLE
[BUG] onPlaneDetected not working as intended

### ISSUE THREAD

**Issue by gtfargo** [HippoAR/react-native-arkit#142]
`onPlaneDetected` gives a plane position set to the starting camera orientation. I've tried positioning based on `positionAbsolute`, `position`, `node`, and `center`.  The plane will always appear centered on the `debug` 3d axis.

**Comment by macrozone** [comment]
This is actually the behavior in arkit itself, but i am not sure why.


Solution is to use onPlaneUpdated, which you should use anyway

**Comment by gtfargo** [comment]
Strange, but solved.  `onPlaneUpdated` works!
