### ISSUE TITLE
Question: how to use react-native-arkit as optional library

### ISSUE THREAD

**Issue by michbil** [HippoAR/react-native-arkit#143]
I'm currently trying to integrate react-native-arkit into the existing application. ARkit feature is strictly optional, so i want it to work only on compatible devices.
Now if I'm trying to start app on iOS 10, i'm getting this error
```
dyld: Library not loaded: /System/Library/Frameworks/ARKit.framework/ARKit
``` 
because such framework don't exist on iOS 10.
So question is: how to make ARkit optional, so app can start on older iOS versions without it.

**Comment by macrozone** [comment]
we need to investigate in that. Maybe you could do some research on that?

**Comment by michbil** [comment]
@macrozone Okay, my solution so far is to make ARKit and libRCTArkit frameworks optional.
![image](https://user-images.githubusercontent.com/498193/35765439-4386ca98-08cc-11e8-93ac-04ec5785a09c.png)
Then disable bitcode.
After that app works on both iOS 10 and 11
