### ISSUE TITLE
Positioning at GPS lat,long

### ISSUE THREAD

**Issue by EricPKerr** [HippoAR/react-native-arkit#15]
I'm unsure if this is a capability of ARKit, but is it possible to position an object in the scene at a fixed GPS coordinate?  If so, what would it take to add support for that to this library?

**Comment by macrozone** [comment]
That is not directly supported by ARKit. 

It's possible to use gps coordinates when your scene loads (https://facebook.github.io/react-native/docs/geolocation.html) and use the compass to check the direction (azimut). You can then transform the coordinates from inside your ARView to the real-world, so you can place something at a fixed GPS Location. 

Notice: The accuracy of GPS is only ~1m under really good conditions (e.g. outdoors with clear sky).
