### ISSUE TITLE
Is there any bindings for `detectionImages` from ARkit?

### ISSUE THREAD

**Issue by coulix** [HippoAR/react-native-arkit#153]
https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/2941063-detectionimages 

The idea would be to use flash cards as anchor points to spawn 3d model.

**Comment by macrozone** [comment]
not yet, but should be easy to do:

- bridge this property detectionImages from JS world to ios (its basically an array of strings with the paths to the image assets)
- then we should receive theses nodes in `renderer didAddNode` and `didUpdateNode`, they have a new type `ARImageAnchor`
- handle this new type `ARImageAnchor` there and call onPlaneDetected, or better a new onFeatureDetected or onImageDetected callback

This is actually not that hard and would be a cool Feature to contribute to. PRs would be very welcome!
I don't know when i have time to do it, but it should be doable in 2-3hours.

We could also add support for VerticalPlanes in the same iteration

see also https://github.com/HippoAR/react-native-arkit/issues/124

**Comment by macrozone** [comment]
It‘s coming: https://github.com/HippoAR/react-native-arkit/pull/155

**Comment by macrozone** [comment]
available in https://github.com/HippoAR/react-native-arkit/releases/tag/0.9.0-beta.3
