### ISSUE TITLE
Plane detection callback isn't being called

### ISSUE THREAD

**Issue by aurodatateam** [HippoAR/react-native-arkit#16]
I modified the example to have something like:
```
<ARKit
                    style={{flex: 1}}
                    onPlaneDetected={this.onPlaneDetect}
                    onPlaneUpdate={this.onPlaneDetect}
                    //onPlaneDetected={console.log}
                    //onPlaneUpdate={console.log}
                    debug // debug mode will show feature points detected and 3D axis
                    planeDetection // turn on plane detection
                    lightEstimation // turn on light estimation
                />
```

where there is code such as below for registering the callback in index.ios.js. But "onPlaneDetect()" doesn't get called even though a plane is detected.

```

export default class App extends Component {

    constructor(props) {
        super(props);
        this.onPlaneDetect = this.onPlaneDetect.bind(this);
    }

    onPlaneDetect() {
        console.log("!!! onPlaneDetect");
    }
```

**Comment by macrozone** [comment]
Can you verify with the latest version? (0.2.1 currently)

**Comment by macrozone** [comment]
@aurodatateam  is your issue resolved?

**Comment by aurodatateam** [comment]
Can't really install that version:

Mac-Pro:MyFirstARKitApp$ npm install react-native-arkit@0.2.1
MyFirstARKitApp@0.0.1 
└─┬ react-native-arkit@0.2.1  invalid
  └─┬ color@2.0.0 
    └─┬ color-string@1.5.2 
      └─┬ simple-swizzle@0.2.2 
        └── is-arrayish@0.3.1

**Comment by macrozone** [comment]
@aurodatateam odd. Btw. i just released 0.3.0. Can you check with that?

**Comment by aurodatateam** [comment]
That gave the same error with npm install

**Comment by macrozone** [comment]
@aurodatateam can you try with yarn ? Verify that you have the latest yarn version (1.x.x)

**Comment by seanmadi** [comment]
I seem to be having the same issue. I am just using the example from the ReadMe and the console logs for onPlaneDetected and onPlaneUpdate are never being called. I also have tried using hitTestPlanes and always come back with an empty array. I am on version 0.7.1. Using an iPhone 8.

**Comment by pritasam** [comment]
Hi I am having the same issue using yarn 1.3.2
