### ISSUE TITLE
Any way to reset?

### ISSUE THREAD

**Issue by KjellConnelly** [HippoAR/react-native-arkit#18]
Two situations have come up where I need to be able to reset my scene... 

1) Every now and then, for some reason, my ARKit scene just doesn't show up. I exit the application, and it works the next time. Not sure why. But if I had a reset button, the user could tap it at least without thinking the app just doesn't work.

2) I have a button for resetting the position of the camera. By default, the app loads my scene in front of the user. And this is fine if the user's device is already facing a comfortable position when the app launches, and they stay in that relative area until they are done with the app. But the truth is that they might be on a couch facing straight ahead for awhile, and then want to lay down on their back across the couch, completely changing their position. Or they may be walking somewhere, and the scene gets further and further away. So the user needs a way to reset the scene to be right infront of them again. 

Is there a way to accomplish this... or something that could be added? It seems like once a scene is first rendered, the position of everything stays static. For instance, I haven't been able to update ARKit.box positions. I can make them disappear, but not move. So I don't think recalculating the position of the camera vs where the boxes should be next time will work, as their positions will not update.

**Comment by KjellConnelly** [comment]
Just created a pull request to reset where the scene’s origin is. But that doesn’t fix the issue where I would need to reset the entire scene from scratch (for the case where it simply doesn’t render at all for an unknown reason)

**Comment by macrozone** [comment]
@KjellConnelly 

I have also the first issue. Its reported here https://github.com/HippoAR/react-native-arkit/issues/11

Should we follow in that issue and close this one?

**Comment by KjellConnelly** [comment]
@macrozone ya that’s fine with me. Btw, not that it would actually solve the issue... but if there was a loading prop you could pass onto the ARKit component as the UI for the View, this might at least help the app’s users to see what is going on.. like you could have the prop be a React Component that says ‘Loading...’, and if after 10 seconds, it hasn’t loaded, you could at the very least update the UI to say ‘failed to load. Please reset the app’. Not that this is a great solution, but it would also allow users to have some sort of loading UI so you don’t just get a blank screen.
