### ISSUE TITLE
react-native link react-native-arkit doesn't work

### ISSUE THREAD

**Issue by heaversm** [HippoAR/react-native-arkit#22]
For me, linking this library required running `react-native link`, not `react-native link react-native-arkit` - doing the latter resulted in:

```
Command `link` unrecognized. Make sure that you have run `npm install` and that you are inside a react-native project.
```

**Comment by iMokhles** [comment]
had same issue I just run `yarn` inside my RN project then link worked again
if that didn't help, you should remove `node_modules` before `yarn`

**Comment by macrozone** [comment]
@heaversm is this still an issue?

**Comment by macrozone** [comment]
close because of silence. Please open a new issue, if there is still a problem!
