### ISSUE TITLE
Can't display the Custom model element

### ISSUE THREAD

**Issue by DavoCg** [HippoAR/react-native-arkit#26]
Hi, 

Everything works well on my iPhone except that I can't display the custom element model here : 
```
 <ARKit.Model
       pos={{ x: -0.2, y: 0, z: 0, frame: 'local' }}
       model={{file: 'art.scnassets/ship.scn', scale: 0.01}}/>
```

I added the file to my XCode project by creating a new AR project in XCode and copied the art.sncassets folder to my React Native Project :

<img width="403" alt="capture d ecran 2017-09-11 a 11 22 37" src="https://user-images.githubusercontent.com/5452654/30267652-8c0f1be0-96e3-11e7-9a17-41f646c6b721.png">

I think everything is setted correctly but the ship won't show :/

Does someone have an idea why ?

Thanks for your work !

**Comment by macrozone** [comment]
same here. `NSURL *url = [[NSBundle mainBundle] URLForResource:property[@"file"] withExtension:nil];` returns nil in my case, so its a problem with the ios framework itself. 

How do i bundle scene assets correctly?

**Comment by DavoCg** [comment]
Do you have the same folder architecture and code as I do ?

**Comment by macrozone** [comment]
@DavoCg yes, try rebuilding the app. Try also to manually add the files to "art.scnassets" by right-click, add Files...

I also managed to load dae-files from a server (with textures), if anyone is interested:

(this is just a lazy example and has the issue that the first time you open a model, it won't show, because it still gets downloaded. I need to use proper lifecycle-functions to fix that)

```
import RNFetchBlob from 'react-native-fetch-blob'
import { unzip } from 'react-native-zip-archive'


const ModelWithDownload = ({ pos, modelId }) => {
  const modelUrl = `https://path/to/file/modelId=${modelId}`
  const path = `${RNFetchBlob.fs.dirs.CacheDir}/models/${modelId}/`
  console.log('downloading', modelUrl)
  RNFetchBlob.config({
    fileCache: true,
  })
    // path: `${path}file.zip` })
    .fetch('GET', modelUrl)
    .progress((received, total) => { console.log('progress', received, total, received / total) })
    .then((res) => { // the temp file path
      console.log('The file saved to ', res.path())
      unzip(res.path(), path).then(
        (unzipPath) => {
          console.log(`unzip completed at ${unzipPath}`)
        },
      ).catch(e => console.log('error', e))
    })
  const file = `${path}product-optimized.scnassets/model.dae`
  console.log('file', file)
  return (
    <ARKit.Model
      pos={pos}
      model={{
        scale: 1,
        file,
      }}
    />
  )
}
```

make sure your zip-files are prepared using this guide: https://the-nerd.be/2014/11/07/dynamically-load-collada-files-in-scenekit-at-runtime/


I also needed to adjust react-native-arkit a bit (i will release that with a PR soon):

```
// replace this line here:
 // NSURL *url = [[NSBundle mainBundle] URLForResource:property[@"file"] withExtension:nil];
// with this
    NSURL *url =  [NSURL fileURLWithPath: property[@"file"]];
```

we might check if the file path is absolute and use `fileURLWithPath` in this case.

**Comment by DavoCg** [comment]
Thanks for your code sample that's what I want to do ! 
I'll try to add files manually and I'll let you know ;)

If you want reviews for your PR I can help !

**Comment by macrozone** [comment]
@DavoCg i created a new assets catalog and renamed the extension to scnassets.

**Comment by DavoCg** [comment]
Thanks @macrozone I finally manage to display custom model just by renaming the extension as you told me ! 
I'll try today to upload some zipped .dae samples for eveyone to use them to try the new feature you are implementing

**Comment by macrozone** [comment]
@DavoCg is this resolved now?
