### ISSUE TITLE
Module Broken: Xcode 9 GM deprecated code

### ISSUE THREAD

**Issue by KjellConnelly** [HippoAR/react-native-arkit#33]
RCTARKit.m needs to be updated... beta versions of this module worked with the deprecated code, but now it won't build.

Here are the things I mostly changed (commented out is the old code, and below is the code that runs)

`//ARSessionConfiguration *configuration = self.session.configuration;
    ARWorldTrackingConfiguration *configuration = self.session.configuration;`

`//ARWorldTrackingSessionConfiguration *configuration = self.session.configuration;
    ARWorldTrackingConfiguration *configuration = self.session.configuration;`

`//-(ARWorldTrackingSessionConfiguration *)configuration {
-(ARWorldTrackingConfiguration *)configuration {`

Pretty simple to fix, but just thought I would let you know. There are multiple instances of this happening and if you download Xcode 9GM, you should have all the red errors I did.

**Comment by jzarca01** [comment]
Did you manage to make it past the "ARKitManager.getCameraPosition" error on app launch ?

**Comment by KjellConnelly** [comment]
That is an error I’ve seen before. It has to do with not being able to use the ARKit framework. I forget exactly why, but are you testing on an iOS11 real device?

It also might be that you don’t have the library linked (react-native link). 

I know I saw this error when testing on the simulator on iOS 10.3 before. To circumvent it, I had to comment out the import ARKit and instead do: const ARKit = {}. I also removed the .a file from Xcode linked libraries. This of course made it so I couldn’t use ARKit. But when I was running the simulator, it was it was on my laptop and I just wanted to work on the nonARKit logic and UI. 

But yes, my app runs fine as long as I edited my .m file as I mentioned in the original post. 

This let me work on

**Comment by macrozone** [comment]
@KjellConnelly can you do a pr? I can merge it also to our fork: https://github.com/panter/react-native-arkit

**Comment by KjellConnelly** [comment]
@macrozone Ok done. I already submitted a PR a few days ago to add a new feature. Just pushed the Xcode 9 GM fixes to it too.

**Comment by macrozone** [comment]
@KjellConnelly thx. In general, try to do atomic pull requests. It's easier to review and verify. But focusScene is a reasonable feature, though. I try to merge it on my fork

**Comment by macrozone** [comment]
@KjellConnelly I released it under `@panter/react-native-arkit@0.2.0`

**Comment by eduplus** [comment]
@macrozone Thanks, got it working with GM with your version.

**Comment by qftgtr** [comment]
Fixed by #20
