### ISSUE TITLE
Does motion tracking work with this?

### ISSUE THREAD

**Issue by eurobob** [HippoAR/react-native-arkit#36]
I don't have a capable device yet so I'm not able to play around with it, but I want to achieve something similar to this:

http://inkhunter.tattoo/

Is this possible?

**Comment by macrozone** [comment]
react-native-arkit is based on https://developer.apple.com/arkit/

It's best at finding horizontal surfaces (tables, floors) and place 3d objects on them.

Inkhunter uses "marker-based ar", which is not yet supported directly in arkit: https://stackoverflow.com/questions/44817416/arkit-is-it-possible-to-track-objects-like-with-vuforia

**Comment by macrozone** [comment]
i think we can close this?
