### ISSUE TITLE
ARImage

### ISSUE THREAD

**Issue by ericmorgan1** [HippoAR/react-native-arkit#37]
Is it possible to render an image?
It seems to be part of the library, but the code file is blank and there are no examples.

**Comment by macrozone** [comment]
yeah, its just a dummy file.

you should be able to use models and place an image as a texture on this model, but i haven't tried that.

**Comment by liplylie** [comment]
I was able to render an image. Used photoshop to convert an image to .dae, and then used xcode to convert the .dae to .scn.

**Comment by macrozone** [comment]
There is a texture feature. So you can assign an image as texture on a plane.

@bnjm might help with that
