### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by crubier** [HippoAR/react-native-arkit#38]
After installing on my existing React native app and linking, I get this cryptic crash when I open the view. Here is the log on xcode:

```
libsystem_kernel.dylib`__abort_with_payload:
    0x1855e00a0 <+0>:  mov    x16, #0x209
    0x1855e00a4 <+4>:  svc    #0x80
->  0x1855e00a8 <+8>:  b.lo   0x1855e00c0               ; <+32>
    0x1855e00ac <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1855e00b0 <+16>: mov    x29, sp
    0x1855e00b4 <+20>: bl     0x1855c2238               ; cerror_nocancel
    0x1855e00b8 <+24>: mov    sp, x29
    0x1855e00bc <+28>: ldp    x29, x30, [sp], #0x10
    0x1855e00c0 <+32>: ret    
```

I am using Xcode 9 release and ios 11 release

**Comment by flexy1994** [comment]
I had the same error.
Maybe forgotten to set "Privacy - Camera Usage Description" in the info.plist?

**Comment by crubier** [comment]
@flexy1994 Yes this did the trick thank you ! 

The need to add this privacy setting is not documented on `react-native-arkit` I believe.

**Comment by flexy1994** [comment]
@crubier you're right.
This is not documented in the repoitory. I found this in the Tutorial linked in the readme.

[Tutorial](https://medium.com/@HippoAR/how-to-make-your-own-arkit-app-in-5-minutes-using-react-native-9d7ce109a4c2)
