### ISSUE TITLE
Loading Online Model

### ISSUE THREAD

**Issue by silverboyir** [HippoAR/react-native-arkit#39]
Hi
i need to load models online and from website 
is there any way to that ?

**Comment by macrozone** [comment]
yes.

See my comment here: https://github.com/HippoAR/react-native-arkit/issues/26#issuecomment-328611061

and the linked gist.

**Comment by macrozone** [comment]
@silverboyir could you use this example? We are planning to add some more examples and recipes like that. If its solved for you, can you close this issue?

**Comment by silverboyir** [comment]
Sorry ,I cant test it now , we are now in feasibility phase

**Comment by macrozone** [comment]
this is already doable, but we definitly need a guide/examples section
