### ISSUE TITLE
Suggestion: Make the usage more React familiar without refs

### ISSUE THREAD

**Issue by grsabreu** [HippoAR/react-native-arkit#4]
What about changing the usage to a more React-like approach? I mean, the creation of the elements would be determined by their usage as children of the ARKit component. 
It's a suggestion @qftgtr , if you agree I can PR you on this.

```js
import React, { Component } from 'react';
import { AppRegistry, View } from 'react-native';
import ARKit from 'react-native-arkit';

export default function RNARKit() {
  return (
    <View style={{ flex: 1 }}>
      <ARKit
        style={{ flex: 1 }}
        debug
        planeDetection
        lightEstimation
        onPlaneDetected={console.log} // event listener for plane detection
        onPlaneUpdate={console.log} // event listener for plane update
      />

      <ARKit.Text x={0} y={0} z={0} width={0.1} height={0.1} length={0.1} chamfer={0.01}>
        ARKit is cool!
      </ARKit.Text>
      <ARKit.Sphere x={0.2} y={0} z={0} width={0.1} radius={0.05} />
      <ARKit.Plane x={0.4} y={0.4} z={0} width={0.1} height={0.1} />
    </View>
  );
}

AppRegistry.registerComponent('ReactNativeARKit', () => ReactNativeARKit);
```

**Comment by nikolal** [comment]
Completely agree with this. +1

**Comment by qftgtr** [comment]
Hi @grsabreu , this is a very good suggestion! I believe the React approach is better, especially when handling multiple objects in the scene. Thank you and I would really appreciate your PR.

**Comment by greis** [comment]
@grsabreu That is a really great idea. It could even match some of the components in React VR https://facebook.github.io/react-vr/docs/getting-started.html

**Comment by grsabreu** [comment]
awesome! thanks @qftgtr 
sorry I did not had time for it
