### ISSUE TITLE
ARKit.xx components can be used everywhere

### ISSUE THREAD

**Issue by macrozone** [HippoAR/react-native-arkit#44]
I accidentially mounted an ARKit.Box outside of the ARKit component and did not notice, because it actually works

The reason is, that we only allow one ARKit-scene and its internally a singleton

It still feels a bit odd though ;-) should we restrict mounting these components inside the ARKit-component?

**Comment by qftgtr** [comment]
Yes this is indeed the case. However, it might be useful in some case. For example, if you want to have a button that user can press it to place a 3D cube, have the `<Button>` and `<ARKit.Box>` together may be better.
