### ISSUE TITLE
[Feature] Group

### ISSUE THREAD

**Issue by macrozone** [HippoAR/react-native-arkit#45]
Add a ARKit.Group that can contain multiple nodes. 

at start it should only be to organize multiple elements into one component, but later we can think about allowing position and rotation on that group that will affect every element inside.

**Comment by qftgtr** [comment]
`ARKit.Group` is a really nice feature to have!

I think this can be done using a `SCNNode`. We attach `ARKit.Group`'s children under that node, and position and rotation applied on the node will affect every child.

**Comment by macrozone** [comment]
It has been available for some time, but now can also receive all the SCNNode properties!
