### ISSUE TITLE
React-native-arkit & measurement app?

### ISSUE THREAD

**Issue by Mboisgard** [HippoAR/react-native-arkit#5]
Hi,

Great job in implementing this tool! It's seems great. Cannot wait to test it :-)

I saw this application running with ARKit written in Swift 4.0 : https://github.com/duzexu/ARuler

Do you think it's possible to make the same app with react-native-arkit?

Thanks a lot!

**Comment by macrozone** [comment]
@Mboisgard best head over to the slack channel for these kind of questions: react-native-ar.slack.com

**Comment by jackychanfox** [comment]
how can I join to the slack channel?
I need to make measure app with react-native.
please help me if someone done this before
