### ISSUE TITLE
[Question] Click event on plane to set an anchor

### ISSUE THREAD

**Issue by dittmarconsulting** [HippoAR/react-native-arkit#61]
Hi there,

First of all well done for this library. It's a very exciting topic indeed and with the RN hype at the moment it will certainly gain traction in no time.

I have been playing around with ARKit and had the look at the ios source code. I can see that you used `SCNNode` and `ARPlaneAnchor` for the `Plane.update` function.

Is it possible to click on the mobile screen to set an anchor and get the X,Y,Z position of this point on the plane?

Thank you very much.

Cheers,
Tom

**Comment by macrozone** [comment]
yes. This is possible:

```
 ARKit.hitTestPlanes(
  { x, y },
  ARKit.ARHitTestResultType.ExistingPlane
).then(({ results }) => {
  // results is a list of hit results. first one is nearest (e.g. a table)
  // last one is farthest, e.g. the floor
});

```

**Comment by dittmarconsulting** [comment]
Thanks for your fast replay @macrozone 

Can you tell me where would it get the x,y coordinates from? (screen position?)

**Comment by macrozone** [comment]
@dittmarconsulting ARKit only supports horizontal planes. It can't detect edges or walls.

If you need to know where a wall is, you need the help from the user. E.g. make him draw a line on the floor where the wall is. Then you can place a vertical plane there and do hit-testing with that.

**Comment by gino8080** [comment]
@macrozone could you please give a complete example of using it?

thank you very much

**Comment by macrozone** [comment]
@gino8080 best ask general usage question in the slack channel: https://join.slack.com/t/react-native-ar/shared_invite/enQtMjUzMzg3MjM0MTQ5LWU3Nzg2YjI4MGRjMTM1ZDBlNmIwYTE4YmM0M2U0NmY2YjBiYzQ4YzlkODExMTA0NDkwMzFhYWY4ZDE2M2Q4NGY
