### ISSUE TITLE
[Feature] Expose Camera Rotation

### ISSUE THREAD

**Issue by nikgraf** [HippoAR/react-native-arkit#67]
I'm using getCameraPosition. It would be great to also retrieve the camera rotation. Is this possible?

**Comment by macrozone** [comment]
yes, will do a pr for that.

**Comment by macrozone** [comment]
There is a new `readCamera` function that returns all camera properties. Can you check if this works for you? I can reopen the issue if not.

**Comment by cropd** [comment]
When I use the new `getCamera` function it always returns `0` for `x` and `z` except for the camera position.


```
ARKit.getCamera().then(function (camera) {

    console.log("CAMERA EULERANGLES: ");
    console.log(camera.eulerAngles);

    console.log("CAMERA POSITION: ");
    console.log(camera.position);

    console.log("CAMERA ORIENTATION: ");
    console.log(camera.orientation);

    console.log("CAMERA ROTATION: ");
    console.log(camera.rotation);

})
```

console.log:

> App.js:36 CAMERA EULERANGLES: 
> App.js:37 {z: 0, y: 2.419349431991577, x: 0}
> App.js:39 CAMERA POSITION: 
> App.js:40 {z: -11.366372108459473, y: -16.15921401977539, x: 16.728076934814453}
> App.js:42 CAMERA ORIENTATION: 
> App.js:43 {y: 0.9355010986328125, w: 0.35332372784614563, z: 0, x: 0}
> App.js:45 CAMERA ROTATION: 
> App.js:46 {y: 0.9999999403953552, w: 2.419349431991577, z: 0, x: 0}
