### ISSUE TITLE
does addModel works?

### ISSUE THREAD

**Issue by xyx2011** [HippoAR/react-native-arkit#7]
Hey, Thanks for doing this. I pulled the latest from git and try to use addModel function. I added something like this: `this.arkit.addModel({ x: 0.5, y: 0.7, z: 0, fontSize: 0.1, depth: 0.05, file: '../../3dAssets/Woola.OBJ' });` but get `undefined is not a object`. what's file format should be? Thanks for help!

**Comment by bnjm** [comment]
Looks like it was added to the readme since you posted, 

> SceneKit only supports .scn and .dae formats.
