### ISSUE TITLE
[Feature] Light and shadow support

### ISSUE THREAD

**Issue by bnjm** [HippoAR/react-native-arkit#77]
It would be great for react-native-arkit to support shadows, which as far as I can tell are not possible yet. Scenekit requires at least one SCNLight node in the scene with castsShadow set to true.  

Docs for SCNLight: https://developer.apple.com/documentation/scenekit/scnlight

Imagined implementation: `<AR.Light position={{}} castsShadow type={'ambient'}.../>`

**Comment by macrozone** [comment]
yeah, should be straight forward to implement. 

We might think about how we can make it easier to transfer properties from react code to the scenekit code. 

RCTConvert+ARKit is a way, where you define how  json objects are parsed to any objective-c class.

One problem i realized is, that while its great to create new instances on scenekit, updating existing objects feels not so intuitive.

Maybe we find a even better architecture to do so.
