### ISSUE TITLE
Undefined is not an object (evaluating ARKitManager.getCameraPosition)

### ISSUE THREAD

**Issue by Cattalyya** [HippoAR/react-native-arkit#8]
How can I fix this?
Also, from here `const ARKitManager = NativeModules.ARKitManager;` in your `ARKit.js`, I understand that you get ARKitManager from NativeModules from react-native. However, I can't find where is ARKitManager implemented in Facebook's react-native.

**Comment by danleveille** [comment]
@Cattalyya I was running into this same issue. What was your solution?

**Comment by Cattalyya** [comment]
@danleveille I believe that `react-native link react-native-arkit` doesn't work properly. So you have to follow "Manual installation" section for ios. [This article](https://medium.com/@HippoAR/how-to-make-your-own-arkit-app-in-5-minutes-using-react-native-9d7ce109a4c2) has more detailed on setup. Make sure that all requirements such as xcode and ios version are satisfied.

**Comment by liplylie** [comment]
I also ran into this problem and tried to follow the Manual installation section, which also did not work. 

Please let us know of any solutions!

**Comment by turtec** [comment]
@liplylie Which version are u using? Please check your package.json file. ARKitManager.getCameraPosition should work in version 0.3.0

**Comment by liplylie** [comment]
I was able to find out the problem. I had to put libRCTARKit.a into project --> general --> Linked Frameworks and Libraries in XCode. I also double checked and put a console.log(ARKitManager) in node_modules/react-native-arkit/ARKit.js, and got a response.
