### ISSUE TITLE
where do i put my custom file?

### ISSUE THREAD

**Issue by SuperDuperMartin** [HippoAR/react-native-arkit#9]
i tried putting it in ios/3dAssets/
But cant get it to load...

Awesome library btw!

**Comment by qftgtr** [comment]
The model files should be placed in a `*.scnassets` folder. You can look at the SceneKit example by opening a new project and select Application -> Game.

**Comment by SuperDuperMartin** [comment]
thank you! worked great!

**Comment by GeekRishabh** [comment]
@SuperDuperMartin @qftgtr  can you share example ?

**Comment by qftgtr** [comment]
@GeekRishabh Please check https://github.com/HippoAR/ReactNativeARKit for a sample ios project.
