### ISSUE TITLE
xCode:

### ISSUE THREAD

**Issue by benni-t** [HippoAR/react-native-arkit#94]
Hello guys, i have a little problem. When i run the application in xcode, the stuff will be loaded but i get the message: 

2017-10-19 13:39:10.802068+0200 MyFirstARKitApp[435:65378] [] nw_connection_get_connected_socket 4 Connection has no connected handler
2017-10-19 13:39:10.802115+0200 MyFirstARKitApp[435:65378] TCP Conn 0x1c417b300 Failed : error 0:61 [61]

So the content (shapes,...) cannot be loaded. The camera on the phone works and i get the debug mode with the yellow dots and the coordinate system.

Please can you help me!? :)

Thanks a lot

**Comment by daviddarnes** [comment]
@dasbenni you might have to follow the manual installation instructions so the app can find your assets https://github.com/HippoAR/react-native-arkit#manual-installation I'm only guessing though as I'm assuming you installed the app all via the cli?

**Comment by macrozone** [comment]
@benni-t is this still an issue? if so, best ask in the slack channel: react-native-ar.slack.com
